//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgileDevelopmentPlatform
{
    using System;

    public partial class Task
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ProjectId { get; set; }
        public string TaskInitiatorId { get; set; }
        public string ResponsibleUserId { get; set; }
        public Nullable<int> SprintId { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public Nullable<int> WorkEffort { get; set; }
        public Nullable<int> TaskDificultyId { get; set; }
        public Nullable<System.DateTime> TaskCreationDate { get; set; }
        public Nullable<System.DateTime> TaskCompletionDate { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Sprint Sprint { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TaskDificultyLevel TaskDificultyLevel { get; set; }
    }
}
